apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-color
  name: webapp-color
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-color
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp-color
    spec:
      containers:
      - image: odonfack/debian:simple-webapp-color
        name: webapp-color
        volumeMounts:
          - name: example-configmap-volume
            mountPath: /etc/config
      volumes:
       - name: example-configmap-volume
         configMap:
           name: app-config
