apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp-color
  name: webapp-color-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30082
  selector:
    app: webapp-color
  type: NodePort
status:
  loadBalancer: {}
