apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp-color
  name: webapp-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-color
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-color
    spec:
      containers:
      - image: odonfack/debian:simple-webapp-color
        name: webapp-color
        resources: {}
status: {}
